name: test env

on:
  workflow_dispatch:

env:
  TEST: ${{secrets.TEST}}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: changing to directory
        run: cd workflow/module-3/d-4
      - name: Install Dependencies
        run: npm i
      - name: Run test script
        run: node script.js
